from .users import users_bp
from .movies import movies_bp
from .watchlist import watchlist_bp
from .bookings import bookings_bp
from .payments import payments_bp
from .reviews import reviews_bp
from .genres import genres_bp
from .signup import signup_bp
from .login import login_bp
